### ISSUE TITLE
Issues when rendering the book

### ISSUE THREAD

**Issue by CGMossa** [teuder/rcpp4everyone_en#15]
I tried to clone and build this book. I faced to minute issues.

First, `google_analytics.txt`-file is required. Solution: I made an empty txt file with that name, and everything worked. Maybe the actual file contains some important line. 

Second in `_output.yml` it says

```yaml
# ...
documentclass: bxjsbook
classoption: xelatex,ja=standard
geometry: no
```

This is a specific LaTeX document class. It is not available on MikTex, and I've found the repo [here](https://github.com/zr-tex8r/BXjscls). Solution: I commented it out, as it is not strictly necessary (I think!).
